services:
  app:
    image: backend-nest:v1
    container_name: reddit-backend
    env_file:
      - .env.development.local
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    volumes:
      - my-db:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: test
      MYSQL_USER: test
      MYSQL_DATABASE: nest
      MYSQL_ROOT_PASSWORD: test
    ports:
      - 3307:3306
    expose:
      - 3007
      
  minio:
    image: minio/minio:RELEASE.2024-02-24T17-11-14Z
    container_name: minio
    environment:
      MINIO_ROOT_USER: 'minioadmin'
      MINIO_ROOT_PASSWORD: 'minioadmin'
      MINIO_BUCKET: 'reddit-content-posted'
      MINIO_SERVER_URL: "http://host.docker.internal:9010"
    ports:
      - 9010:9000
      - 9011:9001
    restart: unless-stopped
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    
volumes:
  minio_data:
    driver: local
  my-db:
    driver: local

